name: publish

on:
  push:
    tags:
      - '*'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: pnpm install
      - run: pnpm run build
      - run: npm publish --dry-run
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
